### ISSUE TITLE
Published in Google Play Store

### ISSUE THREAD

**Issue by yabdi** [jenthone/hackernews_android#13]
Hello,

This is a wonderful HN reader app and I wanted to know when it will be published in Google Play Store? So far, I am able to run it in  Android Studio emulator and it is little buggy. For example, the top/front page listing doesn't match what's shown in HN Website. Looking forward to using this app when it is ready for release. Thank you.

**Comment by jenthone** [comment]
I have no plan to release or publish this app to Google Play.
